/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteTermsRouteImport } from './routes/_site.terms'
import { Route as SiteServicesRouteImport } from './routes/_site.services'
import { Route as SiteProductsRouteImport } from './routes/_site.products'
import { Route as SitePrivacyRouteImport } from './routes/_site.privacy'
import { Route as SiteHowItWorksRouteImport } from './routes/_site.how-it-works'
import { Route as SiteFaqRouteImport } from './routes/_site.faq'
import { Route as SiteContactRouteImport } from './routes/_site.contact'
import { Route as SiteAboutRouteImport } from './routes/_site.about'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTermsRoute = SiteTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => SiteRoute,
} as any)
const SiteServicesRoute = SiteServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProductsRoute = SiteProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => SiteRoute,
} as any)
const SitePrivacyRoute = SitePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SiteRoute,
} as any)
const SiteHowItWorksRoute = SiteHowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => SiteRoute,
} as any)
const SiteFaqRoute = SiteFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/about': typeof SiteAboutRoute
  '/contact': typeof SiteContactRoute
  '/faq': typeof SiteFaqRoute
  '/how-it-works': typeof SiteHowItWorksRoute
  '/privacy': typeof SitePrivacyRoute
  '/products': typeof SiteProductsRoute
  '/services': typeof SiteServicesRoute
  '/terms': typeof SiteTermsRoute
}
export interface FileRoutesByTo {
  '/about': typeof SiteAboutRoute
  '/contact': typeof SiteContactRoute
  '/faq': typeof SiteFaqRoute
  '/how-it-works': typeof SiteHowItWorksRoute
  '/privacy': typeof SitePrivacyRoute
  '/products': typeof SiteProductsRoute
  '/services': typeof SiteServicesRoute
  '/terms': typeof SiteTermsRoute
  '/': typeof SiteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/_site/about': typeof SiteAboutRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/faq': typeof SiteFaqRoute
  '/_site/how-it-works': typeof SiteHowItWorksRoute
  '/_site/privacy': typeof SitePrivacyRoute
  '/_site/products': typeof SiteProductsRoute
  '/_site/services': typeof SiteServicesRoute
  '/_site/terms': typeof SiteTermsRoute
  '/_site/': typeof SiteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/how-it-works'
    | '/privacy'
    | '/products'
    | '/services'
    | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/contact'
    | '/faq'
    | '/how-it-works'
    | '/privacy'
    | '/products'
    | '/services'
    | '/terms'
    | '/'
  id:
    | '__root__'
    | '/_site'
    | '/_site/about'
    | '/_site/contact'
    | '/_site/faq'
    | '/_site/how-it-works'
    | '/_site/privacy'
    | '/_site/products'
    | '/_site/services'
    | '/_site/terms'
    | '/_site/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/terms': {
      id: '/_site/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof SiteTermsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/services': {
      id: '/_site/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof SiteServicesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/products': {
      id: '/_site/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof SiteProductsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/privacy': {
      id: '/_site/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof SitePrivacyRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/how-it-works': {
      id: '/_site/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof SiteHowItWorksRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/faq': {
      id: '/_site/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof SiteFaqRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteFaqRoute: typeof SiteFaqRoute
  SiteHowItWorksRoute: typeof SiteHowItWorksRoute
  SitePrivacyRoute: typeof SitePrivacyRoute
  SiteProductsRoute: typeof SiteProductsRoute
  SiteServicesRoute: typeof SiteServicesRoute
  SiteTermsRoute: typeof SiteTermsRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteContactRoute: SiteContactRoute,
  SiteFaqRoute: SiteFaqRoute,
  SiteHowItWorksRoute: SiteHowItWorksRoute,
  SitePrivacyRoute: SitePrivacyRoute,
  SiteProductsRoute: SiteProductsRoute,
  SiteServicesRoute: SiteServicesRoute,
  SiteTermsRoute: SiteTermsRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
